### ISSUE TITLE
Crash on Centos7 without sudo privileges

### ISSUE THREAD

**Issue by aviborg** [jormaechea/open-api-mocker#39]
I do not have sudo privileges on my machine so I made a local bin at `` /home/anvib/centos ``` where npm is installed. The npm installation seems to work fine and install open-api-mocker, but running open-api-mocker crashes.

What else do I need?

```
[anvib@machine ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[anvib@machine ~]$ 
[anvib@machine ~]$ 
[anvib@machine ~]$ 
[anvib@machine ~]$ npm i -g open-api-mocker
/home/anvib/centos/usr/bin/open-api-mocker -> /home/anvib/centos/usr/lib/node_modules/open-api-mocker/lib/open-api-mocker-cli.js
/home/anvib/centos/usr/lib
└── open-api-mocker@1.7.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/open-api-mocker/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[anvib@machine ~]$ open-api-mocker -h
/home/anvib/centos/usr/lib/node_modules/open-api-mocker/lib/open-api-mocker-cli.js:51
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

```

**Comment by jormaechea** [comment]
Hi @aviborg.
It looks like it's not a permissions issue, but a syntax error. My guess is that you have a very old version of node that doesn't support the `async` keyword.

Can you run `node --version` and get back just to verify if I'm correct?

Thanks

**Comment by aviborg** [comment]
Oops... 6.16.0 :grimacing:

Used ```yumdownloader --resolve npm``` as I'm on an offline machine. Seems that gave me the old version. Need to figure that out. Thanks for the pointer!

**Comment by jormaechea** [comment]
You're welcome, hope you made it!
